repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.7
  hooks:
    # Run the linter.
    - id: ruff-check
      args: ["--extend-fixable=F841,F401"]
    # Run the formatter.
    - id: ruff-format
