# coding: utf-8

# flake8: noqa

"""
    Ryhti API

    Rakennetun ympäristön tietojärjestelmän rajapinta

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthenticationApi",
    "BindingPlotDivisionMatterApi",
    "BuildingOrdinanceApi",
    "LandUseRestrictionMatterApi",
    "LocalDetailedPlanMatterApi",
    "LocalMasterPlanMatterApi",
    "PlanAttachmentDocumentApi",
    "RegionalPlanMatterApi",
    "StatusApi",
    "UploadedFileApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessToRoad",
    "AdditionalInformation",
    "AdditionalInformationValue",
    "AttachmentDocument",
    "AttributeValue",
    "BindingPlotDivision",
    "BindingPlotDivisionAttachmentDocument",
    "BindingPlotDivisionCancellationInfo",
    "BindingPlotDivisionMatterCreate",
    "BindingPlotDivisionMatterDecision",
    "BindingPlotDivisionMatterPhase",
    "BindingPlotDivisionMatterResponse",
    "BindingPlotDivisionMatterUpdate",
    "BindingPlotDivisionOperator",
    "BoundaryPoint",
    "BuildingOrdinance",
    "BuildingOrdinanceAttachmentDocument",
    "BuildingOrdinanceOperator",
    "CancelledGroupRelations",
    "CodeValue",
    "CustomValidationError",
    "CustomValidationProblemDetails",
    "DecimalRange",
    "DecimalValue",
    "Descriptor",
    "GeneralRegulationGroup",
    "GeoJsonGeometry",
    "GeoJsonLineStringGeometry",
    "GeoJsonMultiLineStringGeometry",
    "GeoJsonMultiPointGeometry",
    "GeoJsonMultiPolygonGeometry",
    "GeoJsonPointGeometry",
    "GeoJsonPolygonGeometry",
    "HandlingEvent",
    "HealthReport",
    "HealthReportEntry",
    "IdentifierValue",
    "InteractionEvent",
    "LandUseRestriction",
    "LandUseRestrictionAttachmentDocument",
    "LandUseRestrictionHandlingEvent",
    "LandUseRestrictionMatterCreate",
    "LandUseRestrictionMatterDecision",
    "LandUseRestrictionMatterPhase",
    "LandUseRestrictionMatterResponse",
    "LandUseRestrictionMatterUpdate",
    "LandUseRestrictionObject",
    "LandUseRestrictionOperator",
    "LanguageString",
    "LocalizedTextValue",
    "MotherProperty",
    "NumericRange",
    "NumericValue",
    "OtherPlanMaterial",
    "ParticipationAndAssessmentScheme",
    "Plan",
    "PlanAttachmentDocument",
    "PlanCancellationInfo",
    "PlanDecision",
    "PlanEffects",
    "PlanMap",
    "PlanMatterCreate",
    "PlanMatterPhase",
    "PlanMatterPhaseResponse",
    "PlanMatterPhaseUriResponse",
    "PlanMatterResponse",
    "PlanMatterUpdate",
    "PlanObject",
    "PlanObjectCancellationInfo",
    "PlanOperator",
    "PlanRecommendation",
    "PlanRegulation",
    "PlanRegulationGroup",
    "PlanRegulationGroupRelations",
    "PlanRegulationValue",
    "PlanReport",
    "PlanSourceData",
    "PlotDivisionPlot",
    "PositiveDecimalRange",
    "PositiveDecimalValue",
    "PositiveNumericRange",
    "PositiveNumericValue",
    "PresentationAlignment",
    "ProblemDetails",
    "RelatedPlan",
    "RelatedPlanObjectRegulationGroupRelation",
    "RelatedPlotDivisionPlot",
    "RelatedRegulationGroupPlanObjectRelation",
    "ReserveBuildingOrdinancePermanentIdentifierCommand",
    "ReserveLocalDetailedPlanMatterPermanentIdentifierCommand",
    "ReserveLocalMasterPlanMatterPermanentIdentifierCommand",
    "ReservePermanentBindingPlotDivisionIdentifierCommand",
    "ReservePermanentLandUseRestrictionIdentifierCommand",
    "ReserveRegionalPlanMatterPermanentIdentifierCommand",
    "RyhtiGeometry",
    "RyhtiGeometryGeometry",
    "SpotElevation",
    "Statute",
    "SuccessResponse",
    "TextValue",
    "TimePeriod",
    "TimePeriodDateOnly",
    "TimePeriodDateOnlyValue",
    "TimePeriodValue",
]

# import apis into sdk package
from ryhti_api_client.xroad_api.authentication_api import AuthenticationApi as AuthenticationApi
from ryhti_api_client.xroad_api.binding_plot_division_matter_api import BindingPlotDivisionMatterApi as BindingPlotDivisionMatterApi
from ryhti_api_client.xroad_api.building_ordinance_api import BuildingOrdinanceApi as BuildingOrdinanceApi
from ryhti_api_client.xroad_api.land_use_restriction_matter_api import LandUseRestrictionMatterApi as LandUseRestrictionMatterApi
from ryhti_api_client.xroad_api.local_detailed_plan_matter_api import LocalDetailedPlanMatterApi as LocalDetailedPlanMatterApi
from ryhti_api_client.xroad_api.local_master_plan_matter_api import LocalMasterPlanMatterApi as LocalMasterPlanMatterApi
from ryhti_api_client.xroad_api.plan_attachment_document_api import PlanAttachmentDocumentApi as PlanAttachmentDocumentApi
from ryhti_api_client.xroad_api.regional_plan_matter_api import RegionalPlanMatterApi as RegionalPlanMatterApi
from ryhti_api_client.xroad_api.status_api import StatusApi as StatusApi
from ryhti_api_client.xroad_api.uploaded_file_api import UploadedFileApi as UploadedFileApi

# import ApiClient
from ryhti_api_client.api_response import ApiResponse as ApiResponse
from ryhti_api_client.api_client import ApiClient as ApiClient
from ryhti_api_client.configuration import Configuration as Configuration
from ryhti_api_client.exceptions import OpenApiException as OpenApiException
from ryhti_api_client.exceptions import ApiTypeError as ApiTypeError
from ryhti_api_client.exceptions import ApiValueError as ApiValueError
from ryhti_api_client.exceptions import ApiKeyError as ApiKeyError
from ryhti_api_client.exceptions import ApiAttributeError as ApiAttributeError
from ryhti_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from ryhti_api_client.models.access_to_road import AccessToRoad as AccessToRoad
from ryhti_api_client.models.additional_information import AdditionalInformation as AdditionalInformation
from ryhti_api_client.models.additional_information_value import AdditionalInformationValue as AdditionalInformationValue
from ryhti_api_client.models.attachment_document import AttachmentDocument as AttachmentDocument
from ryhti_api_client.models.attribute_value import AttributeValue as AttributeValue
from ryhti_api_client.models.binding_plot_division import BindingPlotDivision as BindingPlotDivision
from ryhti_api_client.models.binding_plot_division_attachment_document import BindingPlotDivisionAttachmentDocument as BindingPlotDivisionAttachmentDocument
from ryhti_api_client.models.binding_plot_division_cancellation_info import BindingPlotDivisionCancellationInfo as BindingPlotDivisionCancellationInfo
from ryhti_api_client.models.binding_plot_division_matter_create import BindingPlotDivisionMatterCreate as BindingPlotDivisionMatterCreate
from ryhti_api_client.models.binding_plot_division_matter_decision import BindingPlotDivisionMatterDecision as BindingPlotDivisionMatterDecision
from ryhti_api_client.models.binding_plot_division_matter_phase import BindingPlotDivisionMatterPhase as BindingPlotDivisionMatterPhase
from ryhti_api_client.models.binding_plot_division_matter_response import BindingPlotDivisionMatterResponse as BindingPlotDivisionMatterResponse
from ryhti_api_client.models.binding_plot_division_matter_update import BindingPlotDivisionMatterUpdate as BindingPlotDivisionMatterUpdate
from ryhti_api_client.models.binding_plot_division_operator import BindingPlotDivisionOperator as BindingPlotDivisionOperator
from ryhti_api_client.models.boundary_point import BoundaryPoint as BoundaryPoint
from ryhti_api_client.models.building_ordinance import BuildingOrdinance as BuildingOrdinance
from ryhti_api_client.models.building_ordinance_attachment_document import BuildingOrdinanceAttachmentDocument as BuildingOrdinanceAttachmentDocument
from ryhti_api_client.models.building_ordinance_operator import BuildingOrdinanceOperator as BuildingOrdinanceOperator
from ryhti_api_client.models.cancelled_group_relations import CancelledGroupRelations as CancelledGroupRelations
from ryhti_api_client.models.code_value import CodeValue as CodeValue
from ryhti_api_client.models.custom_validation_error import CustomValidationError as CustomValidationError
from ryhti_api_client.models.custom_validation_problem_details import CustomValidationProblemDetails as CustomValidationProblemDetails
from ryhti_api_client.models.decimal_range import DecimalRange as DecimalRange
from ryhti_api_client.models.decimal_value import DecimalValue as DecimalValue
from ryhti_api_client.models.descriptor import Descriptor as Descriptor
from ryhti_api_client.models.general_regulation_group import GeneralRegulationGroup as GeneralRegulationGroup
from ryhti_api_client.models.geo_json_geometry import GeoJsonGeometry as GeoJsonGeometry
from ryhti_api_client.models.geo_json_line_string_geometry import GeoJsonLineStringGeometry as GeoJsonLineStringGeometry
from ryhti_api_client.models.geo_json_multi_line_string_geometry import GeoJsonMultiLineStringGeometry as GeoJsonMultiLineStringGeometry
from ryhti_api_client.models.geo_json_multi_point_geometry import GeoJsonMultiPointGeometry as GeoJsonMultiPointGeometry
from ryhti_api_client.models.geo_json_multi_polygon_geometry import GeoJsonMultiPolygonGeometry as GeoJsonMultiPolygonGeometry
from ryhti_api_client.models.geo_json_point_geometry import GeoJsonPointGeometry as GeoJsonPointGeometry
from ryhti_api_client.models.geo_json_polygon_geometry import GeoJsonPolygonGeometry as GeoJsonPolygonGeometry
from ryhti_api_client.models.handling_event import HandlingEvent as HandlingEvent
from ryhti_api_client.models.health_report import HealthReport as HealthReport
from ryhti_api_client.models.health_report_entry import HealthReportEntry as HealthReportEntry
from ryhti_api_client.models.identifier_value import IdentifierValue as IdentifierValue
from ryhti_api_client.models.interaction_event import InteractionEvent as InteractionEvent
from ryhti_api_client.models.land_use_restriction import LandUseRestriction as LandUseRestriction
from ryhti_api_client.models.land_use_restriction_attachment_document import LandUseRestrictionAttachmentDocument as LandUseRestrictionAttachmentDocument
from ryhti_api_client.models.land_use_restriction_handling_event import LandUseRestrictionHandlingEvent as LandUseRestrictionHandlingEvent
from ryhti_api_client.models.land_use_restriction_matter_create import LandUseRestrictionMatterCreate as LandUseRestrictionMatterCreate
from ryhti_api_client.models.land_use_restriction_matter_decision import LandUseRestrictionMatterDecision as LandUseRestrictionMatterDecision
from ryhti_api_client.models.land_use_restriction_matter_phase import LandUseRestrictionMatterPhase as LandUseRestrictionMatterPhase
from ryhti_api_client.models.land_use_restriction_matter_response import LandUseRestrictionMatterResponse as LandUseRestrictionMatterResponse
from ryhti_api_client.models.land_use_restriction_matter_update import LandUseRestrictionMatterUpdate as LandUseRestrictionMatterUpdate
from ryhti_api_client.models.land_use_restriction_object import LandUseRestrictionObject as LandUseRestrictionObject
from ryhti_api_client.models.land_use_restriction_operator import LandUseRestrictionOperator as LandUseRestrictionOperator
from ryhti_api_client.models.language_string import LanguageString as LanguageString
from ryhti_api_client.models.localized_text_value import LocalizedTextValue as LocalizedTextValue
from ryhti_api_client.models.mother_property import MotherProperty as MotherProperty
from ryhti_api_client.models.numeric_range import NumericRange as NumericRange
from ryhti_api_client.models.numeric_value import NumericValue as NumericValue
from ryhti_api_client.models.other_plan_material import OtherPlanMaterial as OtherPlanMaterial
from ryhti_api_client.models.participation_and_assessment_scheme import ParticipationAndAssessmentScheme as ParticipationAndAssessmentScheme
from ryhti_api_client.models.plan import Plan as Plan
from ryhti_api_client.models.plan_attachment_document import PlanAttachmentDocument as PlanAttachmentDocument
from ryhti_api_client.models.plan_cancellation_info import PlanCancellationInfo as PlanCancellationInfo
from ryhti_api_client.models.plan_decision import PlanDecision as PlanDecision
from ryhti_api_client.models.plan_effects import PlanEffects as PlanEffects
from ryhti_api_client.models.plan_map import PlanMap as PlanMap
from ryhti_api_client.models.plan_matter_create import PlanMatterCreate as PlanMatterCreate
from ryhti_api_client.models.plan_matter_phase import PlanMatterPhase as PlanMatterPhase
from ryhti_api_client.models.plan_matter_phase_response import PlanMatterPhaseResponse as PlanMatterPhaseResponse
from ryhti_api_client.models.plan_matter_phase_uri_response import PlanMatterPhaseUriResponse as PlanMatterPhaseUriResponse
from ryhti_api_client.models.plan_matter_response import PlanMatterResponse as PlanMatterResponse
from ryhti_api_client.models.plan_matter_update import PlanMatterUpdate as PlanMatterUpdate
from ryhti_api_client.models.plan_object import PlanObject as PlanObject
from ryhti_api_client.models.plan_object_cancellation_info import PlanObjectCancellationInfo as PlanObjectCancellationInfo
from ryhti_api_client.models.plan_operator import PlanOperator as PlanOperator
from ryhti_api_client.models.plan_recommendation import PlanRecommendation as PlanRecommendation
from ryhti_api_client.models.plan_regulation import PlanRegulation as PlanRegulation
from ryhti_api_client.models.plan_regulation_group import PlanRegulationGroup as PlanRegulationGroup
from ryhti_api_client.models.plan_regulation_group_relations import PlanRegulationGroupRelations as PlanRegulationGroupRelations
from ryhti_api_client.models.plan_regulation_value import PlanRegulationValue as PlanRegulationValue
from ryhti_api_client.models.plan_report import PlanReport as PlanReport
from ryhti_api_client.models.plan_source_data import PlanSourceData as PlanSourceData
from ryhti_api_client.models.plot_division_plot import PlotDivisionPlot as PlotDivisionPlot
from ryhti_api_client.models.positive_decimal_range import PositiveDecimalRange as PositiveDecimalRange
from ryhti_api_client.models.positive_decimal_value import PositiveDecimalValue as PositiveDecimalValue
from ryhti_api_client.models.positive_numeric_range import PositiveNumericRange as PositiveNumericRange
from ryhti_api_client.models.positive_numeric_value import PositiveNumericValue as PositiveNumericValue
from ryhti_api_client.models.presentation_alignment import PresentationAlignment as PresentationAlignment
from ryhti_api_client.models.problem_details import ProblemDetails as ProblemDetails
from ryhti_api_client.models.related_plan import RelatedPlan as RelatedPlan
from ryhti_api_client.models.related_plan_object_regulation_group_relation import RelatedPlanObjectRegulationGroupRelation as RelatedPlanObjectRegulationGroupRelation
from ryhti_api_client.models.related_plot_division_plot import RelatedPlotDivisionPlot as RelatedPlotDivisionPlot
from ryhti_api_client.models.related_regulation_group_plan_object_relation import RelatedRegulationGroupPlanObjectRelation as RelatedRegulationGroupPlanObjectRelation
from ryhti_api_client.models.reserve_building_ordinance_permanent_identifier_command import ReserveBuildingOrdinancePermanentIdentifierCommand as ReserveBuildingOrdinancePermanentIdentifierCommand
from ryhti_api_client.models.reserve_local_detailed_plan_matter_permanent_identifier_command import ReserveLocalDetailedPlanMatterPermanentIdentifierCommand as ReserveLocalDetailedPlanMatterPermanentIdentifierCommand
from ryhti_api_client.models.reserve_local_master_plan_matter_permanent_identifier_command import ReserveLocalMasterPlanMatterPermanentIdentifierCommand as ReserveLocalMasterPlanMatterPermanentIdentifierCommand
from ryhti_api_client.models.reserve_permanent_binding_plot_division_identifier_command import ReservePermanentBindingPlotDivisionIdentifierCommand as ReservePermanentBindingPlotDivisionIdentifierCommand
from ryhti_api_client.models.reserve_permanent_land_use_restriction_identifier_command import ReservePermanentLandUseRestrictionIdentifierCommand as ReservePermanentLandUseRestrictionIdentifierCommand
from ryhti_api_client.models.reserve_regional_plan_matter_permanent_identifier_command import ReserveRegionalPlanMatterPermanentIdentifierCommand as ReserveRegionalPlanMatterPermanentIdentifierCommand
from ryhti_api_client.models.ryhti_geometry import RyhtiGeometry as RyhtiGeometry
from ryhti_api_client.models.ryhti_geometry_geometry import RyhtiGeometryGeometry as RyhtiGeometryGeometry
from ryhti_api_client.models.spot_elevation import SpotElevation as SpotElevation
from ryhti_api_client.models.statute import Statute as Statute
from ryhti_api_client.models.success_response import SuccessResponse as SuccessResponse
from ryhti_api_client.models.text_value import TextValue as TextValue
from ryhti_api_client.models.time_period import TimePeriod as TimePeriod
from ryhti_api_client.models.time_period_date_only import TimePeriodDateOnly as TimePeriodDateOnly
from ryhti_api_client.models.time_period_date_only_value import TimePeriodDateOnlyValue as TimePeriodDateOnlyValue
from ryhti_api_client.models.time_period_value import TimePeriodValue as TimePeriodValue
