# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ryhti_api_client.models.plan_effects_plot import PlanEffectsPlot
from typing import Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class PlanEffects(BaseModel):
    """
    Kaavan vaikutukset
    """  # noqa: E501

    not_in_accordance_with_plan: StrictBool = Field(
        description="Onko kaavan mukainen", alias="notInAccordanceWithPlan"
    )
    binding_plot_division_permanent_identifier: Annotated[
        str, Field(min_length=1, strict=True)
    ] = Field(
        description="Tonttijaon tunniste",
        alias="bindingPlotDivisionPermanentIdentifier",
    )
    permanent_plan_identifier: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="Kaavan pysyvä tunniste", alias="permanentPlanIdentifier"
    )
    plan_effects_plots: Optional[List[PlanEffectsPlot]] = Field(
        default=None,
        description="Kaavan vaikutukset tonttijakotonttikohtaisesti",
        alias="planEffectsPlots",
    )
    __properties: ClassVar[List[str]] = [
        "notInAccordanceWithPlan",
        "bindingPlotDivisionPermanentIdentifier",
        "permanentPlanIdentifier",
        "planEffectsPlots",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanEffects from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in plan_effects_plots (list)
        _items = []
        if self.plan_effects_plots:
            for _item_plan_effects_plots in self.plan_effects_plots:
                _items.append(
                    _item_plan_effects_plots.to_dict()
                    if _item_plan_effects_plots is not None
                    else None
                )
            _dict["planEffectsPlots"] = _items
        # set to None if plan_effects_plots (nullable) is None
        # and model_fields_set contains the field
        if (
            self.plan_effects_plots is None
            and "plan_effects_plots" in self.model_fields_set
        ):
            _dict["planEffectsPlots"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanEffects from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "notInAccordanceWithPlan": obj.get("notInAccordanceWithPlan"),
                "bindingPlotDivisionPermanentIdentifier": obj.get(
                    "bindingPlotDivisionPermanentIdentifier"
                ),
                "permanentPlanIdentifier": obj.get("permanentPlanIdentifier"),
                "planEffectsPlots": [
                    PlanEffectsPlot.from_dict(_item)
                    for _item in obj["planEffectsPlots"]
                ]
                if obj.get("planEffectsPlots") is not None
                else None,
            }
        )
        return _obj
