# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class PlanEffectsPlot(BaseModel):
    """
    Liittyvä tonttijakotontti  KaavanVaikutukset Tonttijakotonttikohtaisesti
    """  # noqa: E501

    not_in_accordance_with_plan: StrictBool = Field(
        description="Onko kaavan mukainen", alias="notInAccordanceWithPlan"
    )
    area_reservation_type_uris: Optional[List[StrictStr]] = Field(
        default=None,
        description="Aluevaraus: kaavanmääräyslaji.  Lista kaavanmääräyslajin URI-tunnisteita koodistosta http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji",
        alias="areaReservationTypeUris",
    )
    area_reservation_regulation_uris: Optional[List[StrictStr]] = Field(
        default=None,
        description="Viittaustunnus (https://uri.rakennetunymparistontietojarjestelma.fi/planregulation/{planregulationkey}) kaavassa osoitettuun aluevarauksen kaavamääräykseen.",
        alias="areaReservationRegulationUris",
    )
    volume_of_building_regulation_uris: Optional[List[StrictStr]] = Field(
        default=None,
        description="Viittaustunnus (https://uri.rakennetunymparistontietojarjestelma.fi/planregulation/{planregulationkey})  kaavassa osoitettuun rakentamisen määrän kaavamääräykseen.",
        alias="volumeOfBuildingRegulationUris",
    )
    area_reservation_letter_identifier: Optional[StrictStr] = Field(
        default=None,
        description="Aluevarauksen kirjaintunnus",
        alias="areaReservationLetterIdentifier",
    )
    permitted_building_area: Optional[StrictInt] = Field(
        default=None,
        description="Rakentamisen määrä, kerrosala m2",
        alias="permittedBuildingArea",
    )
    permitted_building_volume: Optional[StrictInt] = Field(
        default=None,
        description="Rakentamisen määrä, rakennustilavuus m3",
        alias="permittedBuildingVolume",
    )
    plot_division_plot_key: Optional[UUID] = Field(
        default=None,
        description="Tonttijakotontin tunniste (PlotDivisionPlotKey), johon kaavan vaikutus kohdistuu.  Pakollinen",
        alias="plotDivisionPlotKey",
    )
    __properties: ClassVar[List[str]] = [
        "notInAccordanceWithPlan",
        "areaReservationTypeUris",
        "areaReservationRegulationUris",
        "volumeOfBuildingRegulationUris",
        "areaReservationLetterIdentifier",
        "permittedBuildingArea",
        "permittedBuildingVolume",
        "plotDivisionPlotKey",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanEffectsPlot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if area_reservation_type_uris (nullable) is None
        # and model_fields_set contains the field
        if (
            self.area_reservation_type_uris is None
            and "area_reservation_type_uris" in self.model_fields_set
        ):
            _dict["areaReservationTypeUris"] = None

        # set to None if area_reservation_regulation_uris (nullable) is None
        # and model_fields_set contains the field
        if (
            self.area_reservation_regulation_uris is None
            and "area_reservation_regulation_uris" in self.model_fields_set
        ):
            _dict["areaReservationRegulationUris"] = None

        # set to None if volume_of_building_regulation_uris (nullable) is None
        # and model_fields_set contains the field
        if (
            self.volume_of_building_regulation_uris is None
            and "volume_of_building_regulation_uris" in self.model_fields_set
        ):
            _dict["volumeOfBuildingRegulationUris"] = None

        # set to None if area_reservation_letter_identifier (nullable) is None
        # and model_fields_set contains the field
        if (
            self.area_reservation_letter_identifier is None
            and "area_reservation_letter_identifier" in self.model_fields_set
        ):
            _dict["areaReservationLetterIdentifier"] = None

        # set to None if permitted_building_area (nullable) is None
        # and model_fields_set contains the field
        if (
            self.permitted_building_area is None
            and "permitted_building_area" in self.model_fields_set
        ):
            _dict["permittedBuildingArea"] = None

        # set to None if permitted_building_volume (nullable) is None
        # and model_fields_set contains the field
        if (
            self.permitted_building_volume is None
            and "permitted_building_volume" in self.model_fields_set
        ):
            _dict["permittedBuildingVolume"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanEffectsPlot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "notInAccordanceWithPlan": obj.get("notInAccordanceWithPlan"),
                "areaReservationTypeUris": obj.get("areaReservationTypeUris"),
                "areaReservationRegulationUris": obj.get(
                    "areaReservationRegulationUris"
                ),
                "volumeOfBuildingRegulationUris": obj.get(
                    "volumeOfBuildingRegulationUris"
                ),
                "areaReservationLetterIdentifier": obj.get(
                    "areaReservationLetterIdentifier"
                ),
                "permittedBuildingArea": obj.get("permittedBuildingArea"),
                "permittedBuildingVolume": obj.get("permittedBuildingVolume"),
                "plotDivisionPlotKey": obj.get("plotDivisionPlotKey"),
            }
        )
        return _obj
