# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Literal, Optional
from typing import Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class PositiveNumericRange(BaseModel):
    """
    PositiveNumericRange
    """  # noqa: E501

    data_type: Literal["PositiveNumericRange"] = Field(
        description='Pakollinen arvo: "PositiveNumericRange"', alias="dataType"
    )
    minimum_value: Optional[StrictInt] = Field(
        default=None, description="Minimiarvo", alias="minimumValue"
    )
    maximum_value: Optional[StrictInt] = Field(
        default=None, description="Maksimiarvo", alias="maximumValue"
    )
    unit_of_measure: Optional[StrictStr] = Field(
        default=None, description="Mittayksikkö", alias="unitOfMeasure"
    )
    __properties: ClassVar[List[str]] = [
        "dataType",
        "minimumValue",
        "maximumValue",
        "unitOfMeasure",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PositiveNumericRange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PositiveNumericRange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "dataType": obj.get("dataType"),
                "minimumValue": obj.get("minimumValue"),
                "maximumValue": obj.get("maximumValue"),
                "unitOfMeasure": obj.get("unitOfMeasure"),
            }
        )
        return _obj
