# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.xroad_api.binding_plot_division_matter_api import BindingPlotDivisionMatterApi


class TestBindingPlotDivisionMatterApi(unittest.TestCase):
    """BindingPlotDivisionMatterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BindingPlotDivisionMatterApi()

    def tearDown(self) -> None:
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_get(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_get

        Sitovan tonttijaon asian hakeminen pysyvällä sitovan tonttijaon tunnuksella.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_get(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_get

        Sitovan tonttijaon asian vaiheen hakeminen avaimella.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_post(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_post

        Rajapinta sitovan tonttijaon asian vaiheen lisäämiseen olemassa olevalle sitovan tonttijaon asialle.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_put(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_put

        Rajapinta jo tallennetun vaiheen päivittämiseen.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_validate_post(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_phase_binding_plot_division_matter_phase_key_validate_post

        Rajapinta sitovan tonttijaon asian vaiheen validoimiseen ilman tallennusta.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_plan_effects_post(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_plan_effects_post

        Rajapinta kaavan vaikutusten luomiseen.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_post(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_post

        Rajapinta sitovan tonttijaon asian luomiseen.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_post_0(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_post_0

        Rajapinta sitovan tonttijaon pysyvän tunnuksen varaamiseen.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_put(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_put

        Rajapinta sitovan tonttijaon asian päivittämiseen.
        """
        pass

    def test_api_binding_plot_division_matter_permanent_binding_plot_division_identifier_validate_post(
        self,
    ) -> None:
        """Test case for api_binding_plot_division_matter_permanent_binding_plot_division_identifier_validate_post

        Rajapinta sitovan tonttijaon asian validoimiseen ilman tallentamista.
        """
        pass


if __name__ == "__main__":
    unittest.main()
