# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.related_regulation_group_plan_object_relation import (
    RelatedRegulationGroupPlanObjectRelation,
)


class TestRelatedRegulationGroupPlanObjectRelation(unittest.TestCase):
    """RelatedRegulationGroupPlanObjectRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> RelatedRegulationGroupPlanObjectRelation:
        """Test RelatedRegulationGroupPlanObjectRelation
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RelatedRegulationGroupPlanObjectRelation`
        """
        model = RelatedRegulationGroupPlanObjectRelation()
        if include_optional:
            return RelatedRegulationGroupPlanObjectRelation(
                related_regulation_group_uri = '',
                plan_object_key = ''
            )
        else:
            return RelatedRegulationGroupPlanObjectRelation(
        )
        """

    def testRelatedRegulationGroupPlanObjectRelation(self):
        """Test RelatedRegulationGroupPlanObjectRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
