# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.plan_object_cancellation_info import (
    PlanObjectCancellationInfo,
)


class TestPlanObjectCancellationInfo(unittest.TestCase):
    """PlanObjectCancellationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanObjectCancellationInfo:
        """Test PlanObjectCancellationInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanObjectCancellationInfo`
        """
        model = PlanObjectCancellationInfo()
        if include_optional:
            return PlanObjectCancellationInfo(
                plan_object_cancellation_info_key = '',
                cancelled_plan_object_uri = '',
                cancels_entire_plan_object = True,
                validity_geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, )
            )
        else:
            return PlanObjectCancellationInfo(
                plan_object_cancellation_info_key = '',
                cancelled_plan_object_uri = '',
                cancels_entire_plan_object = True,
        )
        """

    def testPlanObjectCancellationInfo(self):
        """Test PlanObjectCancellationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
