# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.binding_plot_division_matter_decision import (
    BindingPlotDivisionMatterDecision,
)


class TestBindingPlotDivisionMatterDecision(unittest.TestCase):
    """BindingPlotDivisionMatterDecision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BindingPlotDivisionMatterDecision:
        """Test BindingPlotDivisionMatterDecision
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BindingPlotDivisionMatterDecision`
        """
        model = BindingPlotDivisionMatterDecision()
        if include_optional:
            return BindingPlotDivisionMatterDecision(
                binding_plot_division_matter_decision_key = '',
                binding_plot_division_matter_decision_uri = '',
                decision_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_of_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_of_validity = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decision_documents = [
                    ryhti_api_client.models.binding_plot_division_attachment_document.BindingPlotDivisionAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        binding_plot_division_attachment_document_uri = '', 
                        type_of_attachment = '0', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.binding_plot_division_operator.BindingPlotDivisionOperator(
                                binding_plot_division_operator_key = '', 
                                binding_plot_division_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_binding_plot_division_attachment_documents = [
                            ''
                            ], )
                    ],
                decision_article = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                decision_text = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                name = 'http://uri.suomi.fi/codelist/rytj/AlueidenkayttopaatoksenNimi/code/01',
                decision_identifier = '',
                type_of_decision_maker = '0',
                statute = ryhti_api_client.models.statute.Statute(
                    name_of_statute = null, 
                    number_of_statute_collection = 56, 
                    year_of_statute_collection = 56, 
                    chapter = 56, 
                    section = 56, 
                    subsections = [
                        56
                        ], 
                    paragraphs = [
                        56
                        ], 
                    subparagraphs = [
                        ''
                        ], ),
                decision_maker = ryhti_api_client.models.binding_plot_division_operator.BindingPlotDivisionOperator(
                    binding_plot_division_operator_key = '', 
                    binding_plot_division_operator_uri = '', 
                    first_name = '', 
                    last_name = '', 
                    title = '', 
                    organization_name = '', 
                    business_id = '', )
            )
        else:
            return BindingPlotDivisionMatterDecision(
                binding_plot_division_matter_decision_key = '',
                decision_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_of_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_of_validity = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decision_documents = [
                    ryhti_api_client.models.binding_plot_division_attachment_document.BindingPlotDivisionAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        binding_plot_division_attachment_document_uri = '', 
                        type_of_attachment = '0', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.binding_plot_division_operator.BindingPlotDivisionOperator(
                                binding_plot_division_operator_key = '', 
                                binding_plot_division_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_binding_plot_division_attachment_documents = [
                            ''
                            ], )
                    ],
                name = 'http://uri.suomi.fi/codelist/rytj/AlueidenkayttopaatoksenNimi/code/01',
                type_of_decision_maker = '0',
        )
        """

    def testBindingPlotDivisionMatterDecision(self):
        """Test BindingPlotDivisionMatterDecision"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
