# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.land_use_restriction_object import LandUseRestrictionObject


class TestLandUseRestrictionObject(unittest.TestCase):
    """LandUseRestrictionObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LandUseRestrictionObject:
        """Test LandUseRestrictionObject
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LandUseRestrictionObject`
        """
        model = LandUseRestrictionObject()
        if include_optional:
            return LandUseRestrictionObject(
                land_use_restriction_object_key = '',
                land_use_restriction_object_uri = '',
                related_properties = [
                    ''
                    ],
                related_plans = [
                    ryhti_api_client.models.related_plan.RelatedPlan(
                        related_plan_uri = '', 
                        related_producer_plan_identifier = '', )
                    ],
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, )
            )
        else:
            return LandUseRestrictionObject(
                land_use_restriction_object_key = '',
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
        )
        """

    def testLandUseRestrictionObject(self):
        """Test LandUseRestrictionObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
