# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.plan_effects import PlanEffects


class TestPlanEffects(unittest.TestCase):
    """PlanEffects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanEffects:
        """Test PlanEffects
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanEffects`
        """
        model = PlanEffects()
        if include_optional:
            return PlanEffects(
                type = '0',
                binding_plot_division_uri = '0',
                fully_included = True,
                related_plot_division_plots = [
                    ryhti_api_client.models.related_plot_division_plot.RelatedPlotDivisionPlot(
                        reference_uri = '0', 
                        related_plans = [
                            ryhti_api_client.models.related_plan.RelatedPlan(
                                related_plan_uri = '', 
                                related_producer_plan_identifier = '', )
                            ], 
                        area_reservation_regulation_uris = [
                            ''
                            ], 
                        volume_of_building_regulation_uris = [
                            ''
                            ], )
                    ]
            )
        else:
            return PlanEffects(
                type = '0',
                binding_plot_division_uri = '0',
                related_plot_division_plots = [
                    ryhti_api_client.models.related_plot_division_plot.RelatedPlotDivisionPlot(
                        reference_uri = '0', 
                        related_plans = [
                            ryhti_api_client.models.related_plan.RelatedPlan(
                                related_plan_uri = '', 
                                related_producer_plan_identifier = '', )
                            ], 
                        area_reservation_regulation_uris = [
                            ''
                            ], 
                        volume_of_building_regulation_uris = [
                            ''
                            ], )
                    ],
        )
        """

    def testPlanEffects(self):
        """Test PlanEffects"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
