# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.handling_event import HandlingEvent


class TestHandlingEvent(unittest.TestCase):
    """HandlingEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlingEvent:
        """Test HandlingEvent
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HandlingEvent`
        """
        model = HandlingEvent()
        if include_optional:
            return HandlingEvent(
                handling_event_key = '',
                handling_event_uri = '',
                handling_event_type = 'http://uri.suomi.fi/codelist/rytj/kaavakastap/code/01',
                event_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                description = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                location = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                additional_information_link = '',
                cancelled = True,
                related_documents = [
                    ryhti_api_client.models.plan_attachment_document.PlanAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        plan_attachment_document_uri = '', 
                        type_of_attachment = '0', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.plan_operator.PlanOperator(
                                plan_operator_key = '', 
                                plan_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_plan_attachment_documents = [
                            ''
                            ], )
                    ]
            )
        else:
            return HandlingEvent(
                handling_event_key = '',
                handling_event_type = 'http://uri.suomi.fi/codelist/rytj/kaavakastap/code/01',
        )
        """

    def testHandlingEvent(self):
        """Test HandlingEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
