# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.presentation_alignment import PresentationAlignment


class TestPresentationAlignment(unittest.TestCase):
    """PresentationAlignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PresentationAlignment:
        """Test PresentationAlignment
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PresentationAlignment`
        """
        model = PresentationAlignment()
        if include_optional:
            return PresentationAlignment(
                plan_object_key = '',
                plan_regulation_group_key = '',
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                rotation = 56,
                language = ''
            )
        else:
            return PresentationAlignment(
                plan_object_key = '',
                plan_regulation_group_key = '',
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
        )
        """

    def testPresentationAlignment(self):
        """Test PresentationAlignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
