# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.plan_regulation_value import PlanRegulationValue


class TestPlanRegulationValue(unittest.TestCase):
    """PlanRegulationValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanRegulationValue:
        """Test PlanRegulationValue
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanRegulationValue`
        """
        model = PlanRegulationValue()
        if include_optional:
            return PlanRegulationValue(
                code = '',
                code_list = '',
                title = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                data_type = 'LocalizedText',
                number = 56,
                unit_of_measure = '',
                minimum_value = 1.337,
                maximum_value = 1.337,
                identifier = '',
                register_identifier = '',
                register_name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                text = '',
                syntax = '',
                begin_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return PlanRegulationValue(
                data_type = 'LocalizedText',
        )
        """

    def testPlanRegulationValue(self):
        """Test PlanRegulationValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
