# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.plan_matter_phase import PlanMatterPhase


class TestPlanMatterPhase(unittest.TestCase):
    """PlanMatterPhase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanMatterPhase:
        """Test PlanMatterPhase
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlanMatterPhase`
        """
        model = PlanMatterPhase()
        if include_optional:
            return PlanMatterPhase(
                plan_matter_phase_key = '',
                life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01',
                geographical_area = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                handling_event = ryhti_api_client.models.handling_event.HandlingEvent(
                    handling_event_key = '', 
                    handling_event_uri = '', 
                    handling_event_type = 'http://uri.suomi.fi/codelist/rytj/kaavakastap/code/01', 
                    event_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    name = null, 
                    description = null, 
                    location = null, 
                    additional_information_link = '', 
                    cancelled = True, 
                    related_documents = [
                        ryhti_api_client.models.plan_attachment_document.PlanAttachmentDocument(
                            attachment_document_key = '0', 
                            document_identifier = '0', 
                            name = null, 
                            personal_data_content = '0', 
                            category_of_publicity = '0', 
                            accessibility = True, 
                            retention_time = '0', 
                            confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            languages = [
                                ''
                                ], 
                            file_key = '', 
                            descriptors = [
                                ryhti_api_client.models.descriptor.Descriptor(
                                    descriptor_identifier = '', 
                                    vocabulary = '', 
                                    descriptor = '', )
                                ], 
                            document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            plan_attachment_document_uri = '', 
                            type_of_attachment = '0', 
                            document_specification = null, 
                            document_creator_operators = [
                                ryhti_api_client.models.plan_operator.PlanOperator(
                                    plan_operator_key = '', 
                                    plan_operator_uri = '', 
                                    first_name = '', 
                                    last_name = '', 
                                    title = '', 
                                    organization_name = '', 
                                    business_id = '', )
                                ], 
                            related_plan_attachment_documents = [
                                ''
                                ], )
                        ], ),
                interaction_events = [
                    ryhti_api_client.models.interaction_event.InteractionEvent(
                        interaction_event_key = '', 
                        interaction_event_uri = '', 
                        interaction_event_type = 'http://uri.suomi.fi/codelist/rytj/RY_KaavanVuorovaikutustapahtumanLaji/code/01', 
                        event_time = null, 
                        name = null, 
                        description = null, 
                        location = null, 
                        additional_information_link = '', 
                        cancelled = True, 
                        related_documents = [
                            ryhti_api_client.models.plan_attachment_document.PlanAttachmentDocument(
                                attachment_document_key = '0', 
                                document_identifier = '0', 
                                name = null, 
                                personal_data_content = '0', 
                                category_of_publicity = '0', 
                                accessibility = True, 
                                retention_time = '0', 
                                confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                languages = [
                                    ''
                                    ], 
                                file_key = '', 
                                descriptors = [
                                    ryhti_api_client.models.descriptor.Descriptor(
                                        descriptor_identifier = '', 
                                        vocabulary = '', 
                                        descriptor = '', )
                                    ], 
                                document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                plan_attachment_document_uri = '', 
                                type_of_attachment = '0', 
                                document_specification = null, 
                                document_creator_operators = [
                                    ryhti_api_client.models.plan_operator.PlanOperator(
                                        plan_operator_key = '', 
                                        plan_operator_uri = '', 
                                        first_name = '', 
                                        last_name = '', 
                                        title = '', 
                                        organization_name = '', 
                                        business_id = '', )
                                    ], 
                                related_plan_attachment_documents = [
                                    ''
                                    ], )
                            ], )
                    ],
                plan_decision = ryhti_api_client.models.plan_decision.PlanDecision(
                    plan_decision_key = '', 
                    plan_decision_uri = '', 
                    name = 'http://uri.suomi.fi/codelist/rytj/kaavpaatnimi/code/01', 
                    decision_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    date_of_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    decision_documents = [
                        ryhti_api_client.models.plan_attachment_document.PlanAttachmentDocument(
                            attachment_document_key = '0', 
                            document_identifier = '0', 
                            name = null, 
                            personal_data_content = '0', 
                            category_of_publicity = '0', 
                            accessibility = True, 
                            retention_time = '0', 
                            confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            languages = [
                                ''
                                ], 
                            file_key = '', 
                            descriptors = [
                                ryhti_api_client.models.descriptor.Descriptor(
                                    descriptor_identifier = '', 
                                    vocabulary = '', 
                                    descriptor = '', )
                                ], 
                            document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            plan_attachment_document_uri = '', 
                            type_of_attachment = '0', 
                            document_specification = null, 
                            document_creator_operators = [
                                ryhti_api_client.models.plan_operator.PlanOperator(
                                    plan_operator_key = '', 
                                    plan_operator_uri = '', 
                                    first_name = '', 
                                    last_name = '', 
                                    title = '', 
                                    organization_name = '', 
                                    business_id = '', )
                                ], 
                            related_plan_attachment_documents = [
                                ''
                                ], )
                        ], 
                    decision_article = null, 
                    decision_text = null, 
                    type_of_decision_maker = '0', 
                    decision_identifier = '', 
                    statutes = [
                        ryhti_api_client.models.statute.Statute(
                            name_of_statute = null, 
                            number_of_statute_collection = 56, 
                            year_of_statute_collection = 56, 
                            chapter = 56, 
                            section = 56, 
                            subsections = [
                                56
                                ], 
                            paragraphs = [
                                56
                                ], 
                            subparagraphs = [
                                ''
                                ], )
                        ], 
                    plans = [
                        ryhti_api_client.models.plan.Plan(
                            plan_key = '', 
                            plan_uri = '', 
                            life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01', 
                            legal_effect_of_local_master_plans = [
                                'http://uri.suomi.fi/codelist/rytj/oikeusvaik_YK/code/1'
                                ], 
                            scale = 56, 
                            official_use_only = True, 
                            plan_maps = [
                                ryhti_api_client.models.plan_map.PlanMap(
                                    plan_map_key = '', 
                                    plan_map_uri = '', 
                                    name = null, 
                                    file_key = '0', 
                                    coordinate_system = '0', )
                                ], 
                            geographical_area = null, 
                            plan_description = '', 
                            plan_annexes = [
                                ryhti_api_client.models.plan_attachment_document.PlanAttachmentDocument(
                                    attachment_document_key = '0', 
                                    document_identifier = '0', 
                                    name = null, 
                                    personal_data_content = '0', 
                                    category_of_publicity = '0', 
                                    accessibility = True, 
                                    retention_time = '0', 
                                    confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    languages = [
                                        ''
                                        ], 
                                    file_key = '', 
                                    document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                    plan_attachment_document_uri = '', 
                                    type_of_attachment = '0', 
                                    document_specification = null, )
                                ], 
                            other_plan_materials = [
                                ryhti_api_client.models.other_plan_material.OtherPlanMaterial(
                                    other_plan_material_key = '', 
                                    other_plan_material_uri = '', 
                                    name = null, 
                                    file_key = '', 
                                    other_plan_material_link = '', 
                                    personal_data_content = '0', 
                                    category_of_publicity = '0', )
                                ], 
                            plan_cancellation_infos = [
                                ryhti_api_client.models.plan_cancellation_info.PlanCancellationInfo(
                                    plan_cancellation_info_key = '', 
                                    plan_cancellation_info_uri = '', 
                                    cancelled_plan_uri = '0', 
                                    cancels_entire_plan = True, 
                                    cancelled_group_relations = [
                                        ryhti_api_client.models.cancelled_group_relations.CancelledGroupRelations(
                                            plan_regulation_group_uri = '0', 
                                            plan_object_uri = '0', )
                                        ], 
                                    plan_object_cancellation_infos = [
                                        ryhti_api_client.models.plan_object_cancellation_info.PlanObjectCancellationInfo(
                                            plan_object_cancellation_info_key = '', 
                                            cancelled_plan_object_uri = '', 
                                            cancels_entire_plan_object = True, 
                                            validity_geometry = null, )
                                        ], )
                                ], 
                            plan_report = null, 
                            general_regulation_groups = [
                                ryhti_api_client.models.general_regulation_group.GeneralRegulationGroup(
                                    general_regulation_group_key = '', 
                                    general_regulation_group_uri = '', 
                                    title_of_plan_regulation = null, 
                                    plan_regulations = [
                                        ryhti_api_client.models.plan_regulation.PlanRegulation(
                                            plan_regulation_key = '', 
                                            plan_regulation_uri = '', 
                                            value = null, 
                                            life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01', 
                                            type = 'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue', 
                                            verbal_regulations = [
                                                'http://uri.suomi.fi/codelist/rytj/RY_Sanallisen_Kaavamaarayksen_Laji/code/rakentamistapa'
                                                ], 
                                            additional_informations = [
                                                ryhti_api_client.models.additional_information.AdditionalInformation(
                                                    type = 'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayksen_Lisatiedonlaji/code/tyyppi', )
                                                ], 
                                            related_documents = [
                                                
                                                ], 
                                            plan_themes = [
                                                ''
                                                ], 
                                            period_of_validity = null, 
                                            subject_identifiers = [
                                                ''
                                                ], 
                                            regulation_number = '', )
                                        ], 
                                    plan_recommendations = [
                                        ryhti_api_client.models.plan_recommendation.PlanRecommendation(
                                            plan_recommendation_key = '', 
                                            plan_recommendation_uri = '', 
                                            value = null, 
                                            life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01', 
                                            period_of_validity = null, 
                                            recommendation_number = 56, )
                                        ], 
                                    group_number = 56, )
                                ], 
                            presentation_alignments = [
                                ryhti_api_client.models.presentation_alignment.PresentationAlignment(
                                    plan_object_key = '', 
                                    plan_regulation_group_key = '', 
                                    geometry = null, 
                                    rotation = 56, 
                                    language = '', )
                                ], 
                            period_of_validity = null, 
                            approval_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            planners = [
                                ryhti_api_client.models.plan_operator.PlanOperator(
                                    plan_operator_key = '', 
                                    plan_operator_uri = '', 
                                    first_name = '', 
                                    last_name = '', 
                                    title = '', 
                                    organization_name = '', 
                                    business_id = '', )
                                ], 
                            plan_objects = [
                                ryhti_api_client.models.plan_object.PlanObject(
                                    plan_object_key = '', 
                                    plan_object_uri = '', 
                                    life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01', 
                                    underground_status = '0', 
                                    geometry = null, 
                                    name = null, 
                                    description = null, 
                                    vertical_limit = null, 
                                    related_plan_source_data_keys = [
                                        ''
                                        ], 
                                    related_plan_source_data_uris = [
                                        ''
                                        ], 
                                    period_of_validity = null, 
                                    object_number = 56, 
                                    related_plan_object_keys = [
                                        ''
                                        ], )
                                ], 
                            plan_regulation_groups = [
                                ryhti_api_client.models.plan_regulation_group.PlanRegulationGroup(
                                    plan_regulation_group_key = '', 
                                    plan_regulation_group_uri = '', 
                                    title_of_plan_regulation = null, 
                                    letter_identifier = '', 
                                    plan_regulations = [
                                        ryhti_api_client.models.plan_regulation.PlanRegulation(
                                            plan_regulation_key = '', 
                                            plan_regulation_uri = '', 
                                            life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01', 
                                            type = 'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue', 
                                            period_of_validity = null, 
                                            regulation_number = '', )
                                        ], 
                                    color_number = '', 
                                    group_number = 56, )
                                ], 
                            plan_regulation_group_relations = [
                                ryhti_api_client.models.plan_regulation_group_relations.PlanRegulationGroupRelations(
                                    plan_object_key = '', 
                                    plan_regulation_group_key = '', )
                                ], 
                            related_plan_object_regulation_group_relations = [
                                ryhti_api_client.models.related_plan_object_regulation_group_relation.RelatedPlanObjectRegulationGroupRelation(
                                    related_plan_object_uri = '', 
                                    regulation_group_key = '', )
                                ], 
                            related_regulation_group_plan_object_relations = [
                                ryhti_api_client.models.related_regulation_group_plan_object_relation.RelatedRegulationGroupPlanObjectRelation(
                                    related_regulation_group_uri = '', 
                                    plan_object_key = '', )
                                ], )
                        ], 
                    date_of_validity = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    decision_makers = [
                        
                        ], 
                    plan_cancellation_infos = [
                        ryhti_api_client.models.plan_cancellation_info.PlanCancellationInfo(
                            plan_cancellation_info_key = '', 
                            plan_cancellation_info_uri = '', 
                            cancelled_plan_uri = '0', 
                            cancels_entire_plan = True, )
                        ], )
            )
        else:
            return PlanMatterPhase(
                plan_matter_phase_key = '',
                life_cycle_status = 'http://uri.suomi.fi/codelist/rytj/kaavaelinkaari/code/01',
                geographical_area = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
        )
        """

    def testPlanMatterPhase(self):
        """Test PlanMatterPhase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
