# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.reserve_permanent_land_use_restriction_identifier_command import (
    ReservePermanentLandUseRestrictionIdentifierCommand,
)


class TestReservePermanentLandUseRestrictionIdentifierCommand(unittest.TestCase):
    """ReservePermanentLandUseRestrictionIdentifierCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> ReservePermanentLandUseRestrictionIdentifierCommand:
        """Test ReservePermanentLandUseRestrictionIdentifierCommand
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReservePermanentLandUseRestrictionIdentifierCommand`
        """
        model = ReservePermanentLandUseRestrictionIdentifierCommand()
        if include_optional:
            return ReservePermanentLandUseRestrictionIdentifierCommand(
                administrative_area_identifier = '',
                project_name = ''
            )
        else:
            return ReservePermanentLandUseRestrictionIdentifierCommand(
        )
        """

    def testReservePermanentLandUseRestrictionIdentifierCommand(self):
        """Test ReservePermanentLandUseRestrictionIdentifierCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
