# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.building_ordinance import BuildingOrdinance


class TestBuildingOrdinance(unittest.TestCase):
    """BuildingOrdinance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildingOrdinance:
        """Test BuildingOrdinance
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BuildingOrdinance`
        """
        model = BuildingOrdinance()
        if include_optional:
            return BuildingOrdinance(
                permanent_building_ordinance_identifier = '0',
                building_ordinance_uri = '',
                name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                description = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                administrative_area_identifiers = [
                    ''
                    ],
                approval_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_of_validity = ryhti_api_client.models.time_period_date_only.TimePeriodDateOnly(
                    begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                attachment_documents = [
                    ryhti_api_client.models.building_ordinance_attachment_document.BuildingOrdinanceAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        building_ordinance_attachment_document_uri = '', 
                        type_of_attachment = 'http://uri.suomi.fi/codelist/rytj/asiakirjanLaji/code/01', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.building_ordinance_operator.BuildingOrdinanceOperator(
                                building_ordinance_operator_key = '', 
                                building_ordinance_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_building_ordinance_documents = [
                            ''
                            ], )
                    ]
            )
        else:
            return BuildingOrdinance(
                permanent_building_ordinance_identifier = '0',
                name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                administrative_area_identifiers = [
                    ''
                    ],
                approval_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_of_validity = ryhti_api_client.models.time_period_date_only.TimePeriodDateOnly(
                    begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                attachment_documents = [
                    ryhti_api_client.models.building_ordinance_attachment_document.BuildingOrdinanceAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        building_ordinance_attachment_document_uri = '', 
                        type_of_attachment = 'http://uri.suomi.fi/codelist/rytj/asiakirjanLaji/code/01', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.building_ordinance_operator.BuildingOrdinanceOperator(
                                building_ordinance_operator_key = '', 
                                building_ordinance_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_building_ordinance_documents = [
                            ''
                            ], )
                    ],
        )
        """

    def testBuildingOrdinance(self):
        """Test BuildingOrdinance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
