# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.related_plan import RelatedPlan


class TestRelatedPlan(unittest.TestCase):
    """RelatedPlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RelatedPlan:
        """Test RelatedPlan
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RelatedPlan`
        """
        model = RelatedPlan()
        if include_optional:
            return RelatedPlan(
                related_plan_uri = '',
                related_producer_plan_identifier = ''
            )
        else:
            return RelatedPlan(
        )
        """

    def testRelatedPlan(self):
        """Test RelatedPlan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
