# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.reserve_building_ordinance_permanent_identifier_command import (
    ReserveBuildingOrdinancePermanentIdentifierCommand,
)


class TestReserveBuildingOrdinancePermanentIdentifierCommand(unittest.TestCase):
    """ReserveBuildingOrdinancePermanentIdentifierCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> ReserveBuildingOrdinancePermanentIdentifierCommand:
        """Test ReserveBuildingOrdinancePermanentIdentifierCommand
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReserveBuildingOrdinancePermanentIdentifierCommand`
        """
        model = ReserveBuildingOrdinancePermanentIdentifierCommand()
        if include_optional:
            return ReserveBuildingOrdinancePermanentIdentifierCommand(
                administrative_area_identifier = '',
                project_name = ''
            )
        else:
            return ReserveBuildingOrdinancePermanentIdentifierCommand(
        )
        """

    def testReserveBuildingOrdinancePermanentIdentifierCommand(self):
        """Test ReserveBuildingOrdinancePermanentIdentifierCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
