# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.related_plan_object_regulation_group_relation import (
    RelatedPlanObjectRegulationGroupRelation,
)


class TestRelatedPlanObjectRegulationGroupRelation(unittest.TestCase):
    """RelatedPlanObjectRegulationGroupRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> RelatedPlanObjectRegulationGroupRelation:
        """Test RelatedPlanObjectRegulationGroupRelation
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RelatedPlanObjectRegulationGroupRelation`
        """
        model = RelatedPlanObjectRegulationGroupRelation()
        if include_optional:
            return RelatedPlanObjectRegulationGroupRelation(
                related_plan_object_uri = '',
                regulation_group_key = ''
            )
        else:
            return RelatedPlanObjectRegulationGroupRelation(
                related_plan_object_uri = '',
                regulation_group_key = '',
        )
        """

    def testRelatedPlanObjectRegulationGroupRelation(self):
        """Test RelatedPlanObjectRegulationGroupRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
