# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.xroad_api.uploaded_file_api import UploadedFileApi


class TestUploadedFileApi(unittest.TestCase):
    """UploadedFileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadedFileApi()

    def tearDown(self) -> None:
        pass

    def test_api_file_post(self) -> None:
        """Test case for api_file_post"""
        pass


if __name__ == "__main__":
    unittest.main()
