# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.plot_division_plot import PlotDivisionPlot


class TestPlotDivisionPlot(unittest.TestCase):
    """PlotDivisionPlot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlotDivisionPlot:
        """Test PlotDivisionPlot
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PlotDivisionPlot`
        """
        model = PlotDivisionPlot()
        if include_optional:
            return PlotDivisionPlot(
                plot_division_plot_key = '',
                plot_division_plot_uri = '',
                plot_division_plot_identifier = '0',
                area = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                projected_area = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                area_reservations = [
                    'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue'
                    ],
                area_reservation_letter_identifier = '0',
                volume_of_building = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                mother_properties = [
                    ryhti_api_client.models.mother_property.MotherProperty(
                        property_identifier = '012', 
                        unseparated_parcel_identifier = '', 
                        contained_area = null, 
                        fully_included = True, )
                    ],
                relation_to_basic_property = '',
                related_plans = [
                    ryhti_api_client.models.related_plan.RelatedPlan(
                        related_plan_uri = '', 
                        related_producer_plan_identifier = '', )
                    ],
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                vertical_limit = ryhti_api_client.models.decimal_range.DecimalRange(
                    minimum_value = 1.337, 
                    maximum_value = 1.337, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                area_reservation_regulation_uris = [
                    ''
                    ],
                volume_of_building_regulation_uris = [
                    ''
                    ]
            )
        else:
            return PlotDivisionPlot(
                plot_division_plot_key = '',
                plot_division_plot_identifier = '0',
                area_reservations = [
                    'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue'
                    ],
                area_reservation_letter_identifier = '0',
                volume_of_building = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                mother_properties = [
                    ryhti_api_client.models.mother_property.MotherProperty(
                        property_identifier = '012', 
                        unseparated_parcel_identifier = '', 
                        contained_area = null, 
                        fully_included = True, )
                    ],
                related_plans = [
                    ryhti_api_client.models.related_plan.RelatedPlan(
                        related_plan_uri = '', 
                        related_producer_plan_identifier = '', )
                    ],
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
        )
        """

    def testPlotDivisionPlot(self):
        """Test PlotDivisionPlot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
