# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.access_to_road import AccessToRoad


class TestAccessToRoad(unittest.TestCase):
    """AccessToRoad unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessToRoad:
        """Test AccessToRoad
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccessToRoad`
        """
        model = AccessToRoad()
        if include_optional:
            return AccessToRoad(
                access_to_road_key = '',
                access_to_road_uri = '',
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                plot_division_plot_keys = [
                    ''
                    ]
            )
        else:
            return AccessToRoad(
                access_to_road_key = '',
                geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                plot_division_plot_keys = [
                    ''
                    ],
        )
        """

    def testAccessToRoad(self):
        """Test AccessToRoad"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
