# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.time_period_date_only_value import TimePeriodDateOnlyValue


class TestTimePeriodDateOnlyValue(unittest.TestCase):
    """TimePeriodDateOnlyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimePeriodDateOnlyValue:
        """Test TimePeriodDateOnlyValue
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TimePeriodDateOnlyValue`
        """
        model = TimePeriodDateOnlyValue()
        if include_optional:
            return TimePeriodDateOnlyValue(
                begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                data_type = 'LocalizedText'
            )
        else:
            return TimePeriodDateOnlyValue(
                data_type = 'LocalizedText',
        )
        """

    def testTimePeriodDateOnlyValue(self):
        """Test TimePeriodDateOnlyValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
