# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.mother_property import MotherProperty


class TestMotherProperty(unittest.TestCase):
    """MotherProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MotherProperty:
        """Test MotherProperty
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MotherProperty`
        """
        model = MotherProperty()
        if include_optional:
            return MotherProperty(
                property_identifier = '012',
                unseparated_parcel_identifier = '',
                contained_area = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                fully_included = True
            )
        else:
            return MotherProperty(
                contained_area = ryhti_api_client.models.positive_numeric_value.PositiveNumericValue(
                    number = 56, 
                    unit_of_measure = '', 
                    data_type = 'LocalizedText', ),
                fully_included = True,
        )
        """

    def testMotherProperty(self):
        """Test MotherProperty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
