# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.success_response import SuccessResponse


class TestSuccessResponse(unittest.TestCase):
    """SuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessResponse:
        """Test SuccessResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SuccessResponse`
        """
        model = SuccessResponse()
        if include_optional:
            return SuccessResponse(
                key = '',
                uri = '',
                warnings = [
                    ryhti_api_client.models.custom_validation_error.CustomValidationError(
                        rule_id = '', 
                        message = '', 
                        instance = '', 
                        class_key = '', )
                    ]
            )
        else:
            return SuccessResponse(
        )
        """

    def testSuccessResponse(self):
        """Test SuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
