# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.land_use_restriction_matter_update import (
    LandUseRestrictionMatterUpdate,
)


class TestLandUseRestrictionMatterUpdate(unittest.TestCase):
    """LandUseRestrictionMatterUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LandUseRestrictionMatterUpdate:
        """Test LandUseRestrictionMatterUpdate
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LandUseRestrictionMatterUpdate`
        """
        model = LandUseRestrictionMatterUpdate()
        if include_optional:
            return LandUseRestrictionMatterUpdate(
                permanent_land_use_restriction_identifier = '0',
                name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                land_use_restriction_type = '0',
                time_of_initiation = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                administrative_area_identifiers = [
                    ''
                    ],
                description = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                case_identifiers = [
                    ''
                    ],
                record_numbers = [
                    ''
                    ],
                producer_land_use_restriction_identifier = '',
                matter_annexes = [
                    ryhti_api_client.models.land_use_restriction_attachment_document.LandUseRestrictionAttachmentDocument(
                        attachment_document_key = '0', 
                        document_identifier = '0', 
                        name = null, 
                        personal_data_content = '0', 
                        category_of_publicity = '0', 
                        accessibility = True, 
                        retention_time = '0', 
                        confirmation_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        languages = [
                            ''
                            ], 
                        file_key = '', 
                        descriptors = [
                            ryhti_api_client.models.descriptor.Descriptor(
                                descriptor_identifier = '', 
                                vocabulary = '', 
                                descriptor = '', )
                            ], 
                        document_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        arrived_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        land_use_restriction_attachment_document_uri = '', 
                        type_of_attachment = '0', 
                        document_specification = null, 
                        document_creator_operators = [
                            ryhti_api_client.models.land_use_restriction_operator.LandUseRestrictionOperator(
                                land_use_restriction_operator_key = '', 
                                land_use_restriction_operator_uri = '', 
                                first_name = '', 
                                last_name = '', 
                                title = '', 
                                organization_name = '', 
                                business_id = '', )
                            ], 
                        related_land_use_restriction_documents = [
                            ''
                            ], )
                    ],
                responsible_party = ryhti_api_client.models.land_use_restriction_operator.LandUseRestrictionOperator(
                    land_use_restriction_operator_key = '', 
                    land_use_restriction_operator_uri = '', 
                    first_name = '', 
                    last_name = '', 
                    title = '', 
                    organization_name = '', 
                    business_id = '', ),
                related_land_use_restriction_matters = [
                    ''
                    ]
            )
        else:
            return LandUseRestrictionMatterUpdate(
                permanent_land_use_restriction_identifier = '0',
                name = ryhti_api_client.models.language_string.LanguageString(
                    fin = '', 
                    swe = '', 
                    smn = '', 
                    sms = '', 
                    sme = '', 
                    eng = '', ),
                land_use_restriction_type = '0',
                time_of_initiation = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                administrative_area_identifiers = [
                    ''
                    ],
        )
        """

    def testLandUseRestrictionMatterUpdate(self):
        """Test LandUseRestrictionMatterUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
