# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.geo_json_point_geometry import GeoJsonPointGeometry


class TestGeoJsonPointGeometry(unittest.TestCase):
    """GeoJsonPointGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoJsonPointGeometry:
        """Test GeoJsonPointGeometry
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GeoJsonPointGeometry`
        """
        model = GeoJsonPointGeometry()
        if include_optional:
            return GeoJsonPointGeometry(
                coordinates = [100.0, 0.0],
                type = 'Point'
            )
        else:
            return GeoJsonPointGeometry(
                coordinates = [100.0, 0.0],
                type = 'Point',
        )
        """

    def testGeoJsonPointGeometry(self):
        """Test GeoJsonPointGeometry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
