# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.binding_plot_division import BindingPlotDivision


class TestBindingPlotDivision(unittest.TestCase):
    """BindingPlotDivision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BindingPlotDivision:
        """Test BindingPlotDivision
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BindingPlotDivision`
        """
        model = BindingPlotDivision()
        if include_optional:
            return BindingPlotDivision(
                binding_plot_division_key = '',
                binding_plot_division_uri = '',
                binding_plot_division_cancellation_infos = [
                    ryhti_api_client.models.binding_plot_division_cancellation_info.BindingPlotDivisionCancellationInfo(
                        cancelled_binding_plot_division_uri = '0', 
                        cancels_entire_binding_plot_division = True, 
                        cancelled_plot_division_plot_uris = [
                            ''
                            ], )
                    ],
                plot_division_plots = [
                    ryhti_api_client.models.plot_division_plot.PlotDivisionPlot(
                        plot_division_plot_key = '', 
                        plot_division_plot_uri = '', 
                        plot_division_plot_identifier = '0', 
                        area = null, 
                        projected_area = null, 
                        area_reservations = [
                            'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue'
                            ], 
                        area_reservation_letter_identifier = '0', 
                        volume_of_building = null, 
                        mother_properties = [
                            ryhti_api_client.models.mother_property.MotherProperty(
                                property_identifier = '012', 
                                unseparated_parcel_identifier = '', 
                                contained_area = null, 
                                fully_included = True, )
                            ], 
                        relation_to_basic_property = '', 
                        related_plans = [
                            ryhti_api_client.models.related_plan.RelatedPlan(
                                related_plan_uri = '', 
                                related_producer_plan_identifier = '', )
                            ], 
                        geometry = null, 
                        vertical_limit = null, 
                        area_reservation_regulation_uris = [
                            ''
                            ], 
                        volume_of_building_regulation_uris = [
                            ''
                            ], )
                    ],
                period_of_validity = ryhti_api_client.models.time_period_date_only.TimePeriodDateOnly(
                    begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                geographical_area = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                boundary_points = [
                    ryhti_api_client.models.boundary_point.BoundaryPoint(
                        boundary_point_or_peg_id = '0', 
                        geometry = null, )
                    ],
                accesses_to_road = [
                    ryhti_api_client.models.access_to_road.AccessToRoad(
                        access_to_road_key = '', 
                        access_to_road_uri = '', 
                        geometry = null, 
                        plot_division_plot_keys = [
                            ''
                            ], )
                    ]
            )
        else:
            return BindingPlotDivision(
                binding_plot_division_key = '',
                plot_division_plots = [
                    ryhti_api_client.models.plot_division_plot.PlotDivisionPlot(
                        plot_division_plot_key = '', 
                        plot_division_plot_uri = '', 
                        plot_division_plot_identifier = '0', 
                        area = null, 
                        projected_area = null, 
                        area_reservations = [
                            'http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji/code/asumisenAlue'
                            ], 
                        area_reservation_letter_identifier = '0', 
                        volume_of_building = null, 
                        mother_properties = [
                            ryhti_api_client.models.mother_property.MotherProperty(
                                property_identifier = '012', 
                                unseparated_parcel_identifier = '', 
                                contained_area = null, 
                                fully_included = True, )
                            ], 
                        relation_to_basic_property = '', 
                        related_plans = [
                            ryhti_api_client.models.related_plan.RelatedPlan(
                                related_plan_uri = '', 
                                related_producer_plan_identifier = '', )
                            ], 
                        geometry = null, 
                        vertical_limit = null, 
                        area_reservation_regulation_uris = [
                            ''
                            ], 
                        volume_of_building_regulation_uris = [
                            ''
                            ], )
                    ],
                period_of_validity = ryhti_api_client.models.time_period_date_only.TimePeriodDateOnly(
                    begin = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                geographical_area = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
                boundary_points = [
                    ryhti_api_client.models.boundary_point.BoundaryPoint(
                        boundary_point_or_peg_id = '0', 
                        geometry = null, )
                    ],
        )
        """

    def testBindingPlotDivision(self):
        """Test BindingPlotDivision"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
