# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.decimal_value import DecimalValue


class TestDecimalValue(unittest.TestCase):
    """DecimalValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecimalValue:
        """Test DecimalValue
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DecimalValue`
        """
        model = DecimalValue()
        if include_optional:
            return DecimalValue(
                number = 1.337,
                unit_of_measure = '',
                data_type = 'LocalizedText'
            )
        else:
            return DecimalValue(
                data_type = 'LocalizedText',
        )
        """

    def testDecimalValue(self):
        """Test DecimalValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
