# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from ryhti_api_client.models.partially_cancelled_plan_object_info import (
    PartiallyCancelledPlanObjectInfo,
)


class TestPartiallyCancelledPlanObjectInfo(unittest.TestCase):
    """PartiallyCancelledPlanObjectInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartiallyCancelledPlanObjectInfo:
        """Test PartiallyCancelledPlanObjectInfo
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PartiallyCancelledPlanObjectInfo`
        """
        model = PartiallyCancelledPlanObjectInfo()
        if include_optional:
            return PartiallyCancelledPlanObjectInfo(
                cancelled_plan_uri = '0',
                partially_cancelled_plan_object_uri = '0',
                validity_geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, )
            )
        else:
            return PartiallyCancelledPlanObjectInfo(
                cancelled_plan_uri = '0',
                partially_cancelled_plan_object_uri = '0',
                validity_geometry = ryhti_api_client.models.ryhti_geometry.RyhtiGeometry(
                    srid = '3067', 
                    geometry = null, ),
        )
        """

    def testPartiallyCancelledPlanObjectInfo(self):
        """Test PartiallyCancelledPlanObjectInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
