# coding: utf-8

"""
Ryhti Plan Public Validate API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from pydantic_core import to_jsonable_python

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ryhti_api_client.models.geo_json_line_string_geometry import (
        GeoJsonLineStringGeometry,
    )
    from ryhti_api_client.models.geo_json_multi_line_string_geometry import (
        GeoJsonMultiLineStringGeometry,
    )
    from ryhti_api_client.models.geo_json_multi_point_geometry import (
        GeoJsonMultiPointGeometry,
    )
    from ryhti_api_client.models.geo_json_multi_polygon_geometry import (
        GeoJsonMultiPolygonGeometry,
    )
    from ryhti_api_client.models.geo_json_point_geometry import GeoJsonPointGeometry
    from ryhti_api_client.models.geo_json_polygon_geometry import GeoJsonPolygonGeometry


class GeoJsonGeometry(BaseModel):
    """
    GeoJson geometria (abstrakti luokka, katso toteutukset)
    """  # noqa: E501

    type: StrictStr = Field(description="Tuetut geometriatyypit")
    __properties: ClassVar[List[str]] = ["type"]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "Point",
                "MultiPoint",
                "LineString",
                "MultiLineString",
                "Polygon",
                "MultiPolygon",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('Point', 'MultiPoint', 'LineString', 'MultiLineString', 'Polygon', 'MultiPolygon')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = "type"

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        "LineString": "GeoJsonLineStringGeometry",
        "MultiLineString": "GeoJsonMultiLineStringGeometry",
        "MultiPoint": "GeoJsonMultiPointGeometry",
        "MultiPolygon": "GeoJsonMultiPolygonGeometry",
        "Point": "GeoJsonPointGeometry",
        "Polygon": "GeoJsonPolygonGeometry",
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj.get(cls.__discriminator_property_name)
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(
        cls, json_str: str
    ) -> Optional[
        Union[
            GeoJsonLineStringGeometry,
            GeoJsonMultiLineStringGeometry,
            GeoJsonMultiPointGeometry,
            GeoJsonMultiPolygonGeometry,
            GeoJsonPointGeometry,
            GeoJsonPolygonGeometry,
        ]
    ]:
        """Create an instance of GeoJsonGeometry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(
        cls, obj: Dict[str, Any]
    ) -> Optional[
        Union[
            GeoJsonLineStringGeometry,
            GeoJsonMultiLineStringGeometry,
            GeoJsonMultiPointGeometry,
            GeoJsonMultiPolygonGeometry,
            GeoJsonPointGeometry,
            GeoJsonPolygonGeometry,
        ]
    ]:
        """Create an instance of GeoJsonGeometry from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type == "GeoJsonLineStringGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_line_string_geometry"
            ).GeoJsonLineStringGeometry.from_dict(obj)
        if object_type == "GeoJsonMultiLineStringGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_multi_line_string_geometry"
            ).GeoJsonMultiLineStringGeometry.from_dict(obj)
        if object_type == "GeoJsonMultiPointGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_multi_point_geometry"
            ).GeoJsonMultiPointGeometry.from_dict(obj)
        if object_type == "GeoJsonMultiPolygonGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_multi_polygon_geometry"
            ).GeoJsonMultiPolygonGeometry.from_dict(obj)
        if object_type == "GeoJsonPointGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_point_geometry"
            ).GeoJsonPointGeometry.from_dict(obj)
        if object_type == "GeoJsonPolygonGeometry":
            return import_module(
                "ryhti_api_client.models.geo_json_polygon_geometry"
            ).GeoJsonPolygonGeometry.from_dict(obj)

        raise ValueError(
            "GeoJsonGeometry failed to lookup discriminator value from "
            + json.dumps(obj)
            + ". Discriminator property name: "
            + cls.__discriminator_property_name
            + ", mapping: "
            + json.dumps(cls.__discriminator_value_class_map)
        )
