# coding: utf-8

"""
Ryhti Plan Public Validate API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from ryhti_api_client.models.language_string import LanguageString
from typing import Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class PlanMap(BaseModel):
    """
    Kaavakartta
    """  # noqa: E501

    plan_map_key: UUID = Field(
        description="Tiedon tuottajatahon tietojärjestelmän generoima kohteen versioriippumaton tunnus",
        alias="planMapKey",
    )
    plan_map_uri: Optional[StrictStr] = Field(
        default=None,
        description="Luokan pysyvä URI -muotoinen viittaustunniste (https://uri.rakennetunymparistontietojarjestelma.fi/planmap/{guid})",
        alias="planMapUri",
    )
    name: LanguageString = Field(
        description="Lokalisoitu merkkijono-luokka eri kielille. Lisää vähintään yksi kieli."
    )
    file_key: UUID = Field(alias="fileKey")
    coordinate_system: Annotated[str, Field(min_length=1, strict=True)] = Field(
        alias="coordinateSystem"
    )
    __properties: ClassVar[List[str]] = [
        "planMapKey",
        "planMapUri",
        "name",
        "fileKey",
        "coordinateSystem",
    ]

    @field_validator("coordinate_system")
    def coordinate_system_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            ["http://uri.suomi.fi/codelist/rakrek/ETRS89/code/EPSG3067"]
        ):
            raise ValueError(
                "must be one of enum values ('http://uri.suomi.fi/codelist/rakrek/ETRS89/code/EPSG3067')"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlanMap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "plan_map_uri",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of name
        if self.name:
            _dict["name"] = self.name.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlanMap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "planMapKey": obj.get("planMapKey"),
                "planMapUri": obj.get("planMapUri"),
                "name": LanguageString.from_dict(obj["name"])
                if obj.get("name") is not None
                else None,
                "fileKey": obj.get("fileKey"),
                "coordinateSystem": obj.get("coordinateSystem"),
            }
        )
        return _obj
