# coding: utf-8

"""
Ryhti API

Rakennetun ympäristön tietojärjestelmän rajapinta

The version of the OpenAPI document: 1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from ryhti_api_client.models.building_ordinance import BuildingOrdinance
from ryhti_api_client.models.reserve_building_ordinance_permanent_identifier_command import (
    ReserveBuildingOrdinancePermanentIdentifierCommand,
)
from ryhti_api_client.models.success_response import SuccessResponse

from ryhti_api_client.api_client import ApiClient, RequestSerialized
from ryhti_api_client.api_response import ApiResponse
from ryhti_api_client.rest import RESTResponseType


class BuildingOrdinanceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_get(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(
                description="Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BuildingOrdinance:
        """Rakennusjärjestyksen hakeminen pysyvän yksilöivän tunnuksen perusteella.


        :param permanent_building_ordinance_identifier: Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_get_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "BuildingOrdinance",
            "404": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_get_with_http_info(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(
                description="Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BuildingOrdinance]:
        """Rakennusjärjestyksen hakeminen pysyvän yksilöivän tunnuksen perusteella.


        :param permanent_building_ordinance_identifier: Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_get_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "BuildingOrdinance",
            "404": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_get_without_preload_content(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(
                description="Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rakennusjärjestyksen hakeminen pysyvän yksilöivän tunnuksen perusteella.


        :param permanent_building_ordinance_identifier: Heattavan rakennusjärjestyksen pysyvä yksilöivä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_get_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "BuildingOrdinance",
            "404": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _api_building_ordinance_permanent_building_ordinance_identifier_get_serialize(
        self,
        permanent_building_ordinance_identifier,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if permanent_building_ordinance_identifier is not None:
            _path_params["permanentBuildingOrdinanceIdentifier"] = (
                permanent_building_ordinance_identifier
            )
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # authentication setting
        _auth_settings: List[str] = ["oauth2", "Bearer"]

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/BuildingOrdinance/{permanentBuildingOrdinanceIdentifier}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post(
        self,
        reserve_building_ordinance_permanent_identifier_command: Annotated[
            ReserveBuildingOrdinancePermanentIdentifierCommand,
            Field(
                description="Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Rajapinta rakennusjärjestystunnusten pysyvien ihmisluettavien tunnusten varaamiseen.

        Endpoint on idempotentti. Voit kutsua rajapintaa useita kertoja samoilla parametreilla, ja se palauttaa saman tunnisteen.

        :param reserve_building_ordinance_permanent_identifier_command: Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen. (required)
        :type reserve_building_ordinance_permanent_identifier_command: ReserveBuildingOrdinancePermanentIdentifierCommand
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_serialize(
            reserve_building_ordinance_permanent_identifier_command=reserve_building_ordinance_permanent_identifier_command,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "str",
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post_with_http_info(
        self,
        reserve_building_ordinance_permanent_identifier_command: Annotated[
            ReserveBuildingOrdinancePermanentIdentifierCommand,
            Field(
                description="Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Rajapinta rakennusjärjestystunnusten pysyvien ihmisluettavien tunnusten varaamiseen.

        Endpoint on idempotentti. Voit kutsua rajapintaa useita kertoja samoilla parametreilla, ja se palauttaa saman tunnisteen.

        :param reserve_building_ordinance_permanent_identifier_command: Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen. (required)
        :type reserve_building_ordinance_permanent_identifier_command: ReserveBuildingOrdinancePermanentIdentifierCommand
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_serialize(
            reserve_building_ordinance_permanent_identifier_command=reserve_building_ordinance_permanent_identifier_command,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "str",
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post_without_preload_content(
        self,
        reserve_building_ordinance_permanent_identifier_command: Annotated[
            ReserveBuildingOrdinancePermanentIdentifierCommand,
            Field(
                description="Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen."
            ),
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rajapinta rakennusjärjestystunnusten pysyvien ihmisluettavien tunnusten varaamiseen.

        Endpoint on idempotentti. Voit kutsua rajapintaa useita kertoja samoilla parametreilla, ja se palauttaa saman tunnisteen.

        :param reserve_building_ordinance_permanent_identifier_command: Tiedot jotka tarvitaan pysyvän rakennusjärjestystunnuksen varaamiseen. (required)
        :type reserve_building_ordinance_permanent_identifier_command: ReserveBuildingOrdinancePermanentIdentifierCommand
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_serialize(
            reserve_building_ordinance_permanent_identifier_command=reserve_building_ordinance_permanent_identifier_command,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "str",
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _api_building_ordinance_permanent_building_ordinance_identifier_post_serialize(
        self,
        reserve_building_ordinance_permanent_identifier_command,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if reserve_building_ordinance_permanent_identifier_command is not None:
            _body_params = reserve_building_ordinance_permanent_identifier_command

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(
                ["application/json", "text/json", "application/*+json"]
            )
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ["oauth2", "Bearer"]

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/BuildingOrdinance/PermanentBuildingOrdinanceIdentifier",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post_0(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Rajapinta rakennusjärjestyksen luomiseen.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_0_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post_0_with_http_info(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Rajapinta rakennusjärjestyksen luomiseen.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_0_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_post_0_without_preload_content(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rajapinta rakennusjärjestyksen luomiseen.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_post_0_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "str",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _api_building_ordinance_permanent_building_ordinance_identifier_post_0_serialize(
        self,
        permanent_building_ordinance_identifier,
        building_ordinance,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if permanent_building_ordinance_identifier is not None:
            _path_params["permanentBuildingOrdinanceIdentifier"] = (
                permanent_building_ordinance_identifier
            )
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if building_ordinance is not None:
            _body_params = building_ordinance

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(
                ["application/json", "text/json", "application/*+json"]
            )
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ["oauth2", "Bearer"]

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/BuildingOrdinance/{permanentBuildingOrdinanceIdentifier}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_put(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr, Field(description="Rakennusjärjestyksen pysyvä tunnus.")
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Päivitetty rakennysjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SuccessResponse:
        """Rajapinta rakennusjärjestyksen päivittämiseen.

        Rajapinnalla voi rakennusjärjestyksen tietoja. Pysyvää tunnusta ja hallinnollisen alueen tunnusta ei voi päivittää.

        :param permanent_building_ordinance_identifier: Rakennusjärjestyksen pysyvä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Päivitetty rakennysjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_put_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
            "404": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_put_with_http_info(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr, Field(description="Rakennusjärjestyksen pysyvä tunnus.")
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Päivitetty rakennysjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SuccessResponse]:
        """Rajapinta rakennusjärjestyksen päivittämiseen.

        Rajapinnalla voi rakennusjärjestyksen tietoja. Pysyvää tunnusta ja hallinnollisen alueen tunnusta ei voi päivittää.

        :param permanent_building_ordinance_identifier: Rakennusjärjestyksen pysyvä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Päivitetty rakennysjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_put_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
            "404": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_put_without_preload_content(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr, Field(description="Rakennusjärjestyksen pysyvä tunnus.")
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Päivitetty rakennysjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rajapinta rakennusjärjestyksen päivittämiseen.

        Rajapinnalla voi rakennusjärjestyksen tietoja. Pysyvää tunnusta ja hallinnollisen alueen tunnusta ei voi päivittää.

        :param permanent_building_ordinance_identifier: Rakennusjärjestyksen pysyvä tunnus. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Päivitetty rakennysjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_put_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
            "404": None,
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _api_building_ordinance_permanent_building_ordinance_identifier_put_serialize(
        self,
        permanent_building_ordinance_identifier,
        building_ordinance,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if permanent_building_ordinance_identifier is not None:
            _path_params["permanentBuildingOrdinanceIdentifier"] = (
                permanent_building_ordinance_identifier
            )
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if building_ordinance is not None:
            _body_params = building_ordinance

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(
                ["application/json", "text/json", "application/*+json"]
            )
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ["oauth2", "Bearer"]

        return self.api_client.param_serialize(
            method="PUT",
            resource_path="/api/BuildingOrdinance/{permanentBuildingOrdinanceIdentifier}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_validate_post(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SuccessResponse:
        """Rajapinta rakennusjärjestyksen validoimiseen ilman tallentamista.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_validate_post_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_validate_post_with_http_info(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SuccessResponse]:
        """Rajapinta rakennusjärjestyksen validoimiseen ilman tallentamista.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_validate_post_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def api_building_ordinance_permanent_building_ordinance_identifier_validate_post_without_preload_content(
        self,
        permanent_building_ordinance_identifier: Annotated[
            StrictStr,
            Field(description="Pysyvä yksilöivä tunnus rakennusjärjestykselle."),
        ],
        building_ordinance: Annotated[
            BuildingOrdinance, Field(description="Rakennusjärjestys.")
        ],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
            ],
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Rajapinta rakennusjärjestyksen validoimiseen ilman tallentamista.

        Rakennusjärjestykselle on varattava pysyvä yksilöivä tunnus ennen järjestyksen tuontia Ryhtiin. Pysyvän yksilöivän tunnuksen tulee olla rakennusjärjestyksen pysyvä tunnus.

        :param permanent_building_ordinance_identifier: Pysyvä yksilöivä tunnus rakennusjärjestykselle. (required)
        :type permanent_building_ordinance_identifier: str
        :param building_ordinance: Rakennusjärjestys. (required)
        :type building_ordinance: BuildingOrdinance
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._api_building_ordinance_permanent_building_ordinance_identifier_validate_post_serialize(
            permanent_building_ordinance_identifier=permanent_building_ordinance_identifier,
            building_ordinance=building_ordinance,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "SuccessResponse",
            "400": "ProblemDetails",
            "422": "CustomValidationProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _api_building_ordinance_permanent_building_ordinance_identifier_validate_post_serialize(
        self,
        permanent_building_ordinance_identifier,
        building_ordinance,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:
        _host = None

        _collection_formats: Dict[str, str] = {}

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if permanent_building_ordinance_identifier is not None:
            _path_params["permanentBuildingOrdinanceIdentifier"] = (
                permanent_building_ordinance_identifier
            )
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if building_ordinance is not None:
            _body_params = building_ordinance

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["text/plain", "application/json", "text/json"]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params["Content-Type"] = _content_type
        else:
            _default_content_type = self.api_client.select_header_content_type(
                ["application/json", "text/json", "application/*+json"]
            )
            if _default_content_type is not None:
                _header_params["Content-Type"] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = ["oauth2", "Bearer"]

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/BuildingOrdinance/{permanentBuildingOrdinanceIdentifier}/Validate",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
